import './admin.css'
import { supabase, hasSupabase } from './supabase.js'

const app=document.querySelector('#app')
const defaultContent=[
 {seccion:'hero_subtitle',titulo:'',texto:'PLAYA BRAVA · PUNTA DEL ESTE'},
 {seccion:'intro_title',titulo:'',texto:'Tu lugar en Punta del Este'},
 {seccion:'intro_text',titulo:'',texto:'Un punto de encuentro frente al mar para disfrutar de gastronomía, playa, deporte y experiencias para toda la familia.'},
 {seccion:'location_title',titulo:'',texto:'Parada 30, Playa Brava'},
 {seccion:'location_text',titulo:'',texto:'Playa Brava · Parada 30\nPunta del Este, Uruguay'},
 {seccion:'contact_instagram',titulo:'',texto:'@parada30punta'},
 {seccion:'contact_phone',titulo:'',texto:'+598 98 153 055'},
 {seccion:'contact_email',titulo:'',texto:'info@amexbeachclub.com'}
]

function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function shell(body){app.innerHTML=`<div class="admin-shell"><aside><div class="brand">AMEX<br><span>BEACH CLUB</span><small>PARADA 30</small></div><a href="/">← Ver web</a><button data-tab="contenido">Contenido</button><button data-tab="menu">Menú</button><button data-tab="actividades">Actividades</button><button data-tab="reservas">Reservas</button><button id="logout">Cerrar sesión</button></aside><main><div class="top"><div><small>ADMINISTRACIÓN</small><h1>AMEX Beach Club</h1></div><span id="status"></span></div><div id="panel">${body}</div></main></div>`;document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>loadTab(b.dataset.tab));document.querySelector('#logout').onclick=async()=>{await supabase.auth.signOut();location.reload()}}

async function login(){app.innerHTML=`<div class="login"><div class="login-card"><div class="brand">AMEX<br><span>BEACH CLUB</span><small>PARADA 30</small></div><h1>Panel de administración</h1><p>Ingresá con el usuario administrador de Supabase.</p><form id="login"><input name="email" type="email" placeholder="Email" required><input name="password" type="password" placeholder="Contraseña" required><button>Ingresar</button><div id="err"></div></form></div></div>`;document.querySelector('#login').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);const {error}=await supabase.auth.signInWithPassword({email:f.get('email'),password:f.get('password')});if(error)document.querySelector('#err').textContent=error.message;else location.reload()}}

async function loadTab(tab){const panel=document.querySelector('#panel');document.querySelector('#status').textContent='';if(tab==='contenido')return contentPanel();if(tab==='menu')return menuPanel();if(tab==='actividades')return activitiesPanel();if(tab==='reservas')return reservationsPanel()}

async function contentPanel(){const rows=await get('contenido');const map=new Map(rows.map(r=>[r.seccion,r]));panel.innerHTML=`<section><div class="section-head"><h2>Contenido</h2><p>Editá los textos principales de la web.</p></div><div class="editor">${defaultContent.map(d=>{const r=map.get(d.seccion)||d;return `<label>${d.seccion}<textarea data-id="${r.id||''}" data-sec="${d.seccion}">${esc(r.texto||'')}</textarea></label>`}).join('')}</div><button class="save" id="saveContent">Guardar cambios</button></section>`;document.querySelector('#saveContent').onclick=async()=>{for(const ta of document.querySelectorAll('[data-sec]')){const row={seccion:ta.dataset.sec,titulo:'',texto:ta.value,imagen:''};if(ta.dataset.id)await supabase.from('contenido').update(row).eq('id',ta.dataset.id);else await supabase.from('contenido').insert(row)}notify('Contenido guardado')}

async function menuPanel(){const rows=await get('menu');panel.innerHTML=`<section><div class="section-head"><h2>Menú</h2><p>Agregá y editá platos y precios.</p></div><div id="menuRows">${rows.map(menuRow).join('')}</div><button class="secondary" id="addMenu">+ Agregar plato</button></section>`;document.querySelector('#addMenu').onclick=()=>{document.querySelector('#menuRows').insertAdjacentHTML('beforeend',menuRow({}));bindMenu()};bindMenu()}

function menuRow(r){return `<div class="row" data-id="${r.id||''}"><input data-k="nombre" placeholder="Nombre" value="${esc(r.nombre||'')}"><input data-k="categoria" placeholder="Categoría" value="${esc(r.categoria||'')}"><input data-k="descripcion" placeholder="Descripción" value="${esc(r.descripcion||'')}"><input data-k="precio" type="number" placeholder="Precio" value="${r.precio??''}"><button class="saveRow">Guardar</button><button class="deleteRow">Eliminar</button></div>`}

function bindMenu(){document.querySelectorAll('.saveRow').forEach(b=>b.onclick=async()=>{const row=b.parentElement;const data={};row.querySelectorAll('[data-k]').forEach(i=>data[i.dataset.k]=i.dataset.k==='precio'?Number(i.value||0):i.value);const id=row.dataset.id;const res=id?await supabase.from('menu').update(data).eq('id',id):await supabase.from('menu').insert(data).select().single();if(!id&&res.data)row.dataset.id=res.data.id;notify('Plato guardado')});document.querySelectorAll('.deleteRow').forEach(b=>b.onclick=async()=>{const row=b.parentElement;if(row.dataset.id)await supabase.from('menu').delete().eq('id',row.dataset.id);row.remove()})}

async function activitiesPanel(){const rows=await get('actividades');panel.innerHTML=`<section><div class="section-head"><h2>Actividades</h2><p>Surf, yoga, volley, fútbol y más.</p></div><div id="actRows">${rows.map(r=>`<div class="row" data-id="${r.id||''}"><input data-k="nombre" placeholder="Nombre" value="${esc(r.nombre||'')}"><input data-k="descripcion" placeholder="Descripción" value="${esc(r.descripcion||'')}"><input data-k="orden" type="number" placeholder="Orden" value="${r.orden??''}"><button class="saveRow">Guardar</button><button class="deleteRow">Eliminar</button></div>`).join('')}</div><button class="secondary" id="addAct">+ Agregar actividad</button></section>`;document.querySelector('#addAct').onclick=()=>{document.querySelector('#actRows').insertAdjacentHTML('beforeend',`<div class="row" data-id=""><input data-k="nombre" placeholder="Nombre"><input data-k="descripcion" placeholder="Descripción"><input data-k="orden" type="number" placeholder="Orden"><button class="saveRow">Guardar</button><button class="deleteRow">Eliminar</button></div>`);bindAct()};bindAct()}

function bindAct(){document.querySelectorAll('#actRows .saveRow').forEach(b=>b.onclick=async()=>{const row=b.parentElement,data={};row.querySelectorAll('[data-k]').forEach(i=>data[i.dataset.k]=i.dataset.k==='orden'?Number(i.value||0):i.value);const id=row.dataset.id;const res=id?await supabase.from('actividades').update(data).eq('id',id):await supabase.from('actividades').insert(data).select().single();if(!id&&res.data)row.dataset.id=res.data.id;notify('Actividad guardada')});document.querySelectorAll('#actRows .deleteRow').forEach(b=>b.onclick=async()=>{const row=b.parentElement;if(row.dataset.id)await supabase.from('actividades').delete().eq('id',row.dataset.id);row.remove()})}

async function reservationsPanel(){const rows=await get('reservas');panel.innerHTML=`<section><div class="section-head"><h2>Reservas</h2><p>Las solicitudes enviadas desde la web aparecen acá.</p></div><div class="table-wrap"><table><thead><tr><th>Fecha</th><th>Nombre</th><th>Teléfono</th><th>Personas</th><th>Estado</th><th>Mensaje</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.fecha||'')}</td><td>${esc(r.nombre||'')}</td><td>${esc(r.telefono||'')}</td><td>${r.personas||''}</td><td><select data-id="${r.id}"><option ${r.estado==='pendiente'?'selected':''}>pendiente</option><option ${r.estado==='confirmada'?'selected':''}>confirmada</option><option ${r.estado==='cancelada'?'selected':''}>cancelada</option></select></td><td>${esc(r.mensaje||'')}</td></tr>`).join('')}</tbody></table></div></section>`;document.querySelectorAll('select[data-id]').forEach(s=>s.onchange=async()=>{await supabase.from('reservas').update({estado:s.value}).eq('id',s.dataset.id);notify('Estado actualizado')})}

async function get(table){const {data,error}=await supabase.from(table).select('*').order('id');if(error){notify(error.message,true);return []}return data||[]}
function notify(t,err=false){document.querySelector('#status').textContent=t;document.querySelector('#status').className=err?'err':'ok'}

async function init(){if(!hasSupabase){app.innerHTML='<div class="login"><div class="login-card"><h1>Falta conectar Supabase</h1><p>Verificá las variables de entorno de Vercel y redeployá el proyecto.</p></div></div>';return}const {data}=await supabase.auth.getSession();if(!data.session)return login();shell('');loadTab('contenido')}
init()
