import './admin.css'
import { supabase, hasSupabase } from './supabase.js'
const app=document.querySelector('#app')
const defaultContent=[
 {seccion:'hero_subtitle',texto:'PLAYA BRAVA · PUNTA DEL ESTE'},
 {seccion:'intro_title',texto:'Tu lugar en Punta del Este'},
 {seccion:'intro_text',texto:'Un punto de encuentro frente al mar para disfrutar de gastronomía, playa, deporte y experiencias para toda la familia.'},
 {seccion:'location_title',texto:'Parada 30, Playa Brava'},
 {seccion:'location_text',texto:'Playa Brava · Parada 30\nPunta del Este, Uruguay'},
 {seccion:'contact_instagram',texto:'@amexbeachclub'},
 {seccion:'contact_phone',texto:'+598 94 123 456'},
 {seccion:'contact_email',texto:'info@amexbeachclub.com'},
 {seccion:'gastro_title',texto:'Sabores que completan la experiencia'},
 {seccion:'gastro_text',texto:'Restaurante, bar y sushi con una propuesta pensada para acompañar cada momento frente al mar.'},
 {seccion:'reserve_title',texto:'RESERVÁ TU EXPERIENCIA'},
 {seccion:'reserve_text',texto:'Reservá tu lugar en la playa, tu mesa o tu bungalow y disfrutá Parada 30.'},
 {seccion:'feature_1_title',texto:'SOMBRILLAS'}, {seccion:'feature_1_text',texto:'Equipadas para tu máximo confort.'},
 {seccion:'feature_2_title',texto:'CAMASTROS'}, {seccion:'feature_2_text',texto:'Relajate frente al mar con el mejor servicio.'},
 {seccion:'feature_3_title',texto:'BUNGALOWS'}, {seccion:'feature_3_text',texto:'Espacios privados para disfrutar en grupo.'},
 {seccion:'feature_4_title',texto:'SERVICIO DE PLAYA'}, {seccion:'feature_4_text',texto:'Gastronomía y tragos sin moverte de tu lugar.'},
 {seccion:'feature_5_title',texto:'DUCHAS'}, {seccion:'feature_5_text',texto:'Comodidad y bienestar todo el día.'}
]
const photoKeys=[['hero_image','Foto principal de portada','image'],['hero_video','Video de portada (si está cargado, reemplaza la foto)','video'],['intro_image','Foto de El Beach Club','image'],['gastro_restaurant_image','Foto de Restaurante','image'],['gastro_bar_image','Foto de Bar','image'],['gastro_sushi_image','Foto de Sushi','image'],...Array.from({length:6},(_,i)=>[`gallery_${i+1}`,`Galería ${i+1}`,'image'])]
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function shell(body){app.innerHTML=`<div class="admin-shell"><aside><div class="brand">AMEX<br><span>BEACH CLUB</span><small>PARADA 30</small></div><a href="/">← Ver web</a><button data-tab="contenido">Contenido</button><button data-tab="fotos">Fotos</button><button data-tab="menu">Menú</button><button data-tab="actividades">Actividades</button><button data-tab="reservas">Reservas</button><button id="logout">Cerrar sesión</button></aside><main><div class="top"><div><small>ADMINISTRACIÓN</small><h1>AMEX Beach Club</h1></div><span id="status"></span></div><div id="panel">${body}</div></main></div>`;document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>loadTab(b.dataset.tab));document.querySelector('#logout').onclick=async()=>{await supabase.auth.signOut();location.reload()}}
async function login(){app.innerHTML=`<div class="login"><div class="login-card"><div class="brand">AMEX<br><span>BEACH CLUB</span><small>PARADA 30</small></div><h1>Panel de administración</h1><p>Ingresá con el usuario administrador de Supabase.</p><form id="login"><input name="email" type="email" placeholder="Email" required><input name="password" type="password" placeholder="Contraseña" required><button>Ingresar</button><div id="err"></div></form></div></div>`;document.querySelector('#login').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);const {error}=await supabase.auth.signInWithPassword({email:f.get('email'),password:f.get('password')});if(error)document.querySelector('#err').textContent=error.message;else location.reload()}}
async function loadTab(tab){if(tab==='contenido')return contentPanel();if(tab==='fotos')return photosPanel();if(tab==='menu')return menuPanel();if(tab==='actividades')return activitiesPanel();if(tab==='reservas')return reservationsPanel()}
async function contentPanel(){const rows=await get('contenido');const map=new Map(rows.map(r=>[r.seccion,r]));document.querySelector('#panel').innerHTML=`<section><div class="section-head"><h2>Contenido</h2><p>Editá los textos principales de la web.</p></div><div class="editor">${defaultContent.map(d=>{const r=map.get(d.seccion)||d;return `<label>${d.seccion}<textarea data-id="${r.id||''}" data-sec="${d.seccion}">${esc(r.texto||'')}</textarea></label>`}).join('')}</div><button class="save" id="saveContent">Guardar cambios</button></section>`;document.querySelector('#saveContent').onclick=async()=>{for(const ta of document.querySelectorAll('[data-sec]')){const row={seccion:ta.dataset.sec,titulo:'',texto:ta.value,imagen:''};const res=ta.dataset.id?await supabase.from('contenido').update(row).eq('id',ta.dataset.id):await supabase.from('contenido').insert(row);if(res.error)return notify(res.error.message,true)}notify('Contenido guardado')}}
async function photosPanel(){const rows=await get('contenido');const map=new Map(rows.map(r=>[r.seccion,r]));document.querySelector('#panel').innerHTML=`<section><div class="section-head"><h2>Fotos y video</h2><p>Podés cambiar la portada y las demás imágenes desde acá. En la portada, si cargás un video, se mostrará el video en lugar de la foto.</p></div><div class="photo-grid">${photoKeys.map(([key,label,type])=>{const r=map.get(key)||{};const media=r.texto||'';const position=r.titulo||'center';const preview=type==='video'?(media?`<video class="admin-video-preview" src="${esc(media)}" muted playsinline controls style="object-position:${esc(position)}"></video>`:'Sin video'):(media?'':'Sin foto');return `<div class="photo-card" data-key="${key}" data-id="${r.id||''}" data-type="${type}"><div class="photo-preview ${type==='video'?'is-video':''}" ${type==='image'&&media?`style="background-image:url('${esc(media)}');background-position:${esc(position)}"`:''}>${preview}</div><strong>${label}</strong><input type="file" accept="${type==='video'?'video/mp4,video/webm,.mp4,.webm':'image/*'}" data-file>${type==='image'?`<label class="position-control">Posición de la foto<select data-position><option value="center" ${position==='center'?'selected':''}>Centro</option><option value="top" ${position==='top'?'selected':''}>Arriba</option><option value="bottom" ${position==='bottom'?'selected':''}>Abajo</option><option value="left" ${position==='left'?'selected':''}>Izquierda</option><option value="right" ${position==='right'?'selected':''}>Derecha</option></select></label>`:''}<button class="saveRow" data-upload>${type==='video'?'Subir video':'Subir foto'}</button>${type==='video'&&media?'<button class="deleteRow" data-clear>Desactivar video</button>':''}</div>`}).join('')}</div></section>`;document.querySelectorAll('[data-upload]').forEach(b=>b.onclick=()=>uploadMedia(b.closest('.photo-card')));document.querySelectorAll('[data-clear]').forEach(b=>b.onclick=()=>clearMedia(b.closest('.photo-card')));document.querySelectorAll('[data-position]').forEach(s=>s.onchange=()=>savePhotoPosition(s.closest('.photo-card'),s.value))}
async function savePhotoPosition(card,position){if(!card.dataset.id)return notify('Primero guardá una foto',true);const {error}=await supabase.from('contenido').update({titulo:position}).eq('id',card.dataset.id);if(error)return notify(error.message,true);notify('Posición guardada')}
async function uploadMedia(card){const input=card.querySelector('[data-file]');if(!input.files[0])return notify(card.dataset.type==='video'?'Elegí un video primero':'Elegí una foto primero',true);const file=input.files[0];if(card.dataset.type==='video'&&!['video/mp4','video/webm'].includes(file.type))return notify('El video debe ser MP4 o WebM',true);if(card.dataset.type==='video'&&file.size>50*1024*1024)return notify('El video debe pesar menos de 50 MB',true);const ext=(file.name.split('.').pop()||'bin').toLowerCase();const path=`${card.dataset.key}/${Date.now()}-${crypto.randomUUID()}.${ext}`;notify(card.dataset.type==='video'?'Subiendo video...':'Subiendo foto...');const {error:up}=await supabase.storage.from('amex-images').upload(path,file,{upsert:false,contentType:file.type});if(up)return notify(up.message,true);const {data}=supabase.storage.from('amex-images').getPublicUrl(path);const currentPosition=card.querySelector('[data-position]')?.value||'center';const payload={seccion:card.dataset.key,titulo:currentPosition,texto:data.publicUrl,imagen:data.publicUrl};let res=card.dataset.id?await supabase.from('contenido').update(payload).eq('id',card.dataset.id):await supabase.from('contenido').insert(payload).select().single();if(res.error)return notify(res.error.message,true);if(res.data)card.dataset.id=res.data.id;const preview=card.querySelector('.photo-preview');if(card.dataset.type==='video'){preview.innerHTML=`<video class="admin-video-preview" src="${esc(data.publicUrl)}" muted playsinline controls></video>`;preview.style.backgroundImage='none';if(!card.querySelector('[data-clear]')){const b=document.createElement('button');b.className='deleteRow';b.dataset.clear='';b.textContent='Desactivar video';b.onclick=()=>clearMedia(card);card.appendChild(b)}}else{preview.style.backgroundImage=`url('${data.publicUrl}')`;preview.style.backgroundPosition=currentPosition;preview.textContent=''}notify(card.dataset.type==='video'?'Video guardado':'Foto guardada')}
async function clearMedia(card){if(!card.dataset.id)return;const res=await supabase.from('contenido').update({titulo:'',texto:'',imagen:''}).eq('id',card.dataset.id);if(res.error)return notify(res.error.message,true);const preview=card.querySelector('.photo-preview');preview.style.backgroundImage='none';preview.innerHTML='Sin video';const clear=card.querySelector('[data-clear]');if(clear)clear.remove();notify('Video desactivado; se usará la foto de portada')}
async function menuPanel(){const rows=await get('menu');document.querySelector('#panel').innerHTML=`<section><div class="section-head"><h2>Menú</h2><p>Agregá y editá platos y precios.</p></div><div id="menuRows">${rows.map(menuRow).join('')}</div><button class="secondary" id="addMenu">+ Agregar plato</button></section>`;document.querySelector('#addMenu').onclick=()=>{document.querySelector('#menuRows').insertAdjacentHTML('beforeend',menuRow({}));bindMenu()};bindMenu()}
function menuRow(r){return `<div class="row" data-id="${r.id||''}"><input data-k="nombre" placeholder="Nombre" value="${esc(r.nombre||'')}"><input data-k="categoria" placeholder="Categoría" value="${esc(r.categoria||'')}"><input data-k="descripcion" placeholder="Descripción" value="${esc(r.descripcion||'')}"><input data-k="precio" type="number" placeholder="Precio" value="${r.precio??''}"><button class="saveRow">Guardar</button><button class="deleteRow">Eliminar</button></div>`}
function bindMenu(){document.querySelectorAll('.saveRow').forEach(b=>b.onclick=async()=>{const row=b.parentElement,data={};row.querySelectorAll('[data-k]').forEach(i=>data[i.dataset.k]=i.dataset.k==='precio'?Number(i.value||0):i.value);const id=row.dataset.id;const res=id?await supabase.from('menu').update(data).eq('id',id):await supabase.from('menu').insert(data).select().single();if(res.error)return notify(res.error.message,true);if(!id&&res.data)row.dataset.id=res.data.id;notify('Plato guardado')});document.querySelectorAll('.deleteRow').forEach(b=>b.onclick=async()=>{const row=b.parentElement;if(row.dataset.id){const res=await supabase.from('menu').delete().eq('id',row.dataset.id);if(res.error)return notify(res.error.message,true)}row.remove()})}
async function activitiesPanel(){const rows=await get('actividades');document.querySelector('#panel').innerHTML=`<section><div class="section-head"><h2>Actividades</h2><p>Surf, yoga, volley, fútbol y más.</p></div><div id="actRows">${rows.map(r=>`<div class="row" data-id="${r.id||''}"><input data-k="nombre" placeholder="Nombre" value="${esc(r.nombre||'')}"><input data-k="descripcion" placeholder="Descripción" value="${esc(r.descripcion||'')}"><input data-k="orden" type="number" placeholder="Orden" value="${r.orden??''}"><button class="saveRow">Guardar</button><button class="deleteRow">Eliminar</button></div>`).join('')}</div><button class="secondary" id="addAct">+ Agregar actividad</button></section>`;document.querySelector('#addAct').onclick=()=>{document.querySelector('#actRows').insertAdjacentHTML('beforeend',`<div class="row" data-id=""><input data-k="nombre" placeholder="Nombre"><input data-k="descripcion" placeholder="Descripción"><input data-k="orden" type="number" placeholder="Orden"><button class="saveRow">Guardar</button><button class="deleteRow">Eliminar</button></div>`);bindAct()};bindAct()}
function bindAct(){document.querySelectorAll('#actRows .saveRow').forEach(b=>b.onclick=async()=>{const row=b.parentElement,data={};row.querySelectorAll('[data-k]').forEach(i=>data[i.dataset.k]=i.dataset.k==='orden'?Number(i.value||0):i.value);const id=row.dataset.id;const res=id?await supabase.from('actividades').update(data).eq('id',id):await supabase.from('actividades').insert(data).select().single();if(res.error)return notify(res.error.message,true);if(!id&&res.data)row.dataset.id=res.data.id;notify('Actividad guardada')});document.querySelectorAll('#actRows .deleteRow').forEach(b=>b.onclick=async()=>{const row=b.parentElement;if(row.dataset.id){const res=await supabase.from('actividades').delete().eq('id',row.dataset.id);if(res.error)return notify(res.error.message,true)}row.remove()})}
async function reservationsPanel(){const rows=await get('reservas');document.querySelector('#panel').innerHTML=`<section><div class="section-head"><h2>Reservas</h2><p>Las solicitudes enviadas desde la web aparecen acá.</p></div><div class="table-wrap"><table><thead><tr><th>Fecha</th><th>Nombre</th><th>Teléfono</th><th>Personas</th><th>Estado</th><th>Mensaje</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.fecha||'')}</td><td>${esc(r.nombre||'')}</td><td>${esc(r.telefono||'')}</td><td>${r.personas||''}</td><td><select data-id="${r.id}"><option ${r.estado==='pendiente'?'selected':''}>pendiente</option><option ${r.estado==='confirmada'?'selected':''}>confirmada</option><option ${r.estado==='cancelada'?'selected':''}>cancelada</option></select></td><td>${esc(r.mensaje||'')}</td></tr>`).join('')}</tbody></table></div></section>`;document.querySelectorAll('select[data-id]').forEach(s=>s.onchange=async()=>{const res=await supabase.from('reservas').update({estado:s.value}).eq('id',s.dataset.id);if(res.error)return notify(res.error.message,true);notify('Estado actualizado')})}
async function get(table){const {data,error}=await supabase.from(table).select('*').order('id');if(error){notify(error.message,true);return []}return data||[]}
function notify(t,err=false){document.querySelector('#status').textContent=t;document.querySelector('#status').className=err?'err':'ok'}
async function init(){if(!hasSupabase){app.innerHTML='<div class="login"><div class="login-card"><h1>Falta conectar Supabase</h1></div></div>';return}const {data}=await supabase.auth.getSession();if(!data.session)return login();shell('');loadTab('contenido')}
init()
